# 思考
有一次，面试的时候，面试官问道socket.io在js端用的时候，问到onerr回调处理，我只是说没有处理

后面在开发中、js也有人们常见语法 try-catch

但是我是一个愚者 一件事没法明白其意义 没法去使用它

## 为什么程序需要一个异常机制

没有异常的时候，程序出错会怎么样?一旦出错，系统会整个崩溃,这有什么问题


  1.出错整个程序就瘫痪了

  2.没法得知错误具体信息

```js
//模拟以前出错代码运行情况
throw new Error('出错了') 
console.log('系统继续运行') //程序不会运行到这里 
```
这里因为用了ES3之后的throw来抛出异常，所以有异常具体信息，之前是没有的

2.如何可以做到尽可能在出错的时候去处理这个错误，告诉系统可以继续运行，并且把错误信息尽可能告知我们
```js
try{
  throw new Error('出错')
}catch(e){
  console.log('捕获到了异常', e)
} 
console.log('系统继续运行') //这里会被运行
```

异常除了让程序不至于整体崩溃，还回答了三个问题：
1.什么出了错 错误堆栈

2.在哪出的错 错误堆栈

3.为什么出错 message

js现有错误类型：
```js
Error 
// 顶级父类 通常作为自定义异常父类使用

EvalError 
// 没有把eval当成函数调用，就会出错 eg: new eval eval由于性能非常之低，使用需要十分谨慎

RangeError
// 数值超出范围 let items = new Array(Number.MAX_VALUE)

ReferenceError 常见
// 访问不存在的变量 let obj = x

SyntaxError 常见
// 语法上不正确

TypeError 常见
//  被操作数的类型不满足此操作 eg: let obj = new 10

URIError
// encodeURI()或decodeURI() URL不符合规范时报错
```    

try-catch-finally
```js
  try{
    // 可能发生异常的代码
    someFunction()
  } catch(error){
    if(error instanceof TypeError){
      //处理类型错误
    } else if (error instanceof ReferenceError) {
      //处理引用错误
    } else {
      //处理其他错误
    }
  } finally {
    // 始终要做的 比如关闭数据库连接
  }
```

抛出错误: throw obj (obj istanceof Error) 通常采用Error子类
```js
  function MyError (message) {
    this.message = message
  }

  MyError.prototype = new Error()

  throw new MyError('我定义的错误')
```

抛出错误的时机:
可能错误的地方

捕获错误的时机:
捕获那些知道怎么处理的错误 一些致命错误



捕获错误的目的在于避免浏览器以默认方式处理它们
抛出错误的目的在于提供错误发生具体原因的消息